%include "colon.inc"

section .rodata

colon "vale_de_este", fourth_word
db "the name of some wine idk", 0

colon "adios_payasos", third_word
db "bye-bye clowns in spanish", 0 

colon "ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm_ummuimumimmu_imimumumuumm", second_word
db "my nickname in steam", 0

colon "order2671", first_word
db "the number of my last order in kfc", 0
