version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: studsss
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0460
    ports:
      - "5439:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realms:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  default:
    driver: bridge